// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjZo341v5GFUBzhIENOM9sDiu7K1tWY4',
    appId: '1:147695898172:android:af2d83f9dc5522f7bf7d39',
    messagingSenderId: '147695898172',
    projectId: 'validation-scanner',
    storageBucket: 'validation-scanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gV_5mMxMEng8HgpSzbaDEhcYj9fdNBc',
    appId: '1:147695898172:ios:6ecaadf14ce527b8bf7d39',
    messagingSenderId: '147695898172',
    projectId: 'validation-scanner',
    storageBucket: 'validation-scanner.appspot.com',
    androidClientId: '147695898172-c7ab9gcsva18ldcpphjs7m3bema0562t.apps.googleusercontent.com',
    iosClientId: '147695898172-bo7sfp8iv8jc47ta8da0p0bp4pun2k0e.apps.googleusercontent.com',
    iosBundleId: 'pt.niaefeup.validationScanner.RunnerTests',
  );
}
